include .env

dev:
	@echo "Running the app..."
	@go run main.go
db:
	@echo "Initializing boostdd database..."
	@psql -h $(DB_HOST) -p $(DB_PORT) -U $(DB_USER) -d postgres \
		-f ./pkg/database/init/init.sql
	@psql -h $(DB_HOST) -p $(DB_PORT) -U $(DB_USER) -d boostdd \
		-f ./pkg/database/init/create.sql
	@psql -h $(DB_HOST) -p $(DB_PORT) -U $(DB_USER) -d boostdd \
		-f ./pkg/database/init/insert.sql
	@psql -h $(DB_HOST) -p $(DB_PORT) -U $(DB_USER) -d boostdd \
		-f ./pkg/database/init/functions.sql
	@echo "Has been successfully created"
build:
	@echo "Building the app, please wait..."
	@go build -o ./bin/boostdd main.go
	@echo "Done."
build-cross:
	@echo "Bulding for windows, linux and macos (darwin m2), please wait..."
	@GOOS=linux GOARCH=amd64 go build -o ./bin/boostdd-linux main.go
	@GOOS=darwin GOARCH=arm64 go build -o ./bin/boostdd-macos main.go
	@GOOS=windows GOARCH=amd64 go build -o ./bin/boostdd-windows main.go
	@echo "Done."
deploy:
	scp ./bin/boostdd-linux ussa@172.16.19.104:/var/www/ussa/
deploy-db:
	scp -r ./database/init ussa@172.16.19.104:/var/www/ussa/
